// <auto-generated> 由 mep_tray/export_revit.py 的 render_cs_constants() 產生，請勿手改。
namespace MepTray.Core;

public static class Fields
{
    public const string SchemaVersion = "schema_version";
    public const string RunId = "run_id";
    public const string Units = "units";
    public const string CoordinateSystem = "coordinate_system";
    public const string Basis = "basis";
    public const string Origin = "origin";
    public const string Unit = "unit";
    public const string AxisX = "axis_x";
    public const string AxisY = "axis_y";
    public const string AxisZ = "axis_z";
    public const string RotationDeg = "rotation_deg";
    public const string Tray = "tray";
    public const string TypeName = "type_name";
    public const string WidthMm = "width_mm";
    public const string HeightMm = "height_mm";
    public const string Kind = "kind";
    public const string Segments = "segments";
    public const string Id = "id";
    public const string Start = "start";
    public const string End = "end";
    public const string Joints = "joints";
    public const string Point = "point";
    public const string SegmentIds = "segments";
    public const string Branch = "branch";
    public const string Hangers = "hangers";
    public const string Findings = "findings";
    public const string SegmentId = "segment_id";
    public const string Status = "status";
    public const string MinLegMm = "min_leg_mm";
    public const string Warnings = "warnings";
    public const string Subject = "subject";
    public const string Suggestion = "suggestion";
    public const string Code = "code";
    public const string Disclosures = "disclosures";
    public const int SchemaVersion_Value = 1;
    public const double RevitMinSegmentMm = 2.54;
    public const double MmPerFoot = 304.8;
    public const string TagOpen = "[MEP-TRAY]";
    public const string TagClose = "[/MEP-TRAY]";
}
