"""Revit Cable Tray 系統族建模匯入器的資料端（中介 JSON）。

不產生 .rfa（見 MANUAL）。本模組只輸出 tray_<run_id>.json；Revit 內建模由 revit/ 下的 C# 匯入器完成。
- 單位 mm；座標原點 = 輸入座標系原點（不平移），與 DXF 同一份座標。mm→英呎只在 C# 端換算一次。
- 主幹在分支接入點被切開，使接點成為多段橋架的共同端點（Tee 才能建立）。
- 座標系基準（Revit 的 Internal Origin / Project Base Point / Shared Coordinates）預設
  UNSPECIFIED，必須由使用者明確指定；匯入器對 UNSPECIFIED 一律拒絕，不自動假定。
- 欄位名稱的單一來源是 FIELDS；Fields.g.cs 由 render_cs_constants() 產生並有契約測試。
"""
from __future__ import annotations

import json
import math
import re
from pathlib import Path

from .disclosure import REVIT_STATUS, base_notes
from .geometry import Vec
from .model import Inputs
from .paths import out_path
from .router import Route, _on_segment

SCHEMA_VERSION = 1
MM_PER_FOOT = 304.8
REVIT_MIN_SEGMENT_MM = 2.54      # Revit 實測錯誤訊息：MEPCurve 最短長度為 1/10 inch
TAG_OPEN, TAG_CLOSE = "[MEP-TRAY]", "[/MEP-TRAY]"
BASES = ("UNSPECIFIED", "INTERNAL_ORIGIN", "PROJECT_BASE_POINT", "SHARED_COORDINATES")
JOINT_KINDS = ("elbow", "tee", "cross", "union", "unsupported")

# 欄位名稱單一來源（C# 常數由此產生）
FIELDS = {
    "SchemaVersion": "schema_version", "RunId": "run_id", "Units": "units",
    "CoordinateSystem": "coordinate_system", "Basis": "basis", "Origin": "origin", "Unit": "unit",
    "AxisX": "axis_x", "AxisY": "axis_y", "AxisZ": "axis_z", "RotationDeg": "rotation_deg",
    "Tray": "tray", "TypeName": "type_name", "WidthMm": "width_mm", "HeightMm": "height_mm",
    "Kind": "kind", "Segments": "segments", "Id": "id", "Start": "start", "End": "end",
    "Joints": "joints", "Point": "point", "SegmentIds": "segments", "Branch": "branch",
    "Hangers": "hangers", "Findings": "findings", "SegmentId": "segment_id", "Status": "status",
    "MinLegMm": "min_leg_mm", "Warnings": "warnings", "Subject": "subject", "Suggestion": "suggestion", "Code": "code", "Disclosures": "disclosures",
}


def render_cs_constants() -> str:
    lines = ["// <auto-generated> 由 mep_tray/export_revit.py 的 render_cs_constants() 產生，請勿手改。",
             "namespace MepTray.Core;", "", "public static class Fields", "{"]
    lines += [f'    public const string {k} = "{v}";' for k, v in FIELDS.items()]
    lines += [f"    public const int SchemaVersion_Value = {SCHEMA_VERSION};",
              f"    public const double RevitMinSegmentMm = {REVIT_MIN_SEGMENT_MM};",
              f"    public const double MmPerFoot = {MM_PER_FOOT};",
              f'    public const string TagOpen = "{TAG_OPEN}";',
              f'    public const string TagClose = "{TAG_CLOSE}";', "}", ""]
    return "\n".join(lines)


def _mm(p) -> list[float]:
    return [round(float(v) * 1000, 3) + 0.0 for v in p]


def split_segments(route: Route) -> list[tuple[Vec, Vec]]:
    """在分支接入點把被接入的主幹段切開（接點成為共同端點）。"""
    segs = list(route.segments)
    for j, _ in route.junctions:
        out = []
        for a, b in segs:
            if j != a and j != b and _on_segment(j, a, b):
                out += [(a, j), (j, b)]
            else:
                out.append((a, b))
        segs = out
    return segs


def _dir(a: Vec, b: Vec) -> tuple[int, int]:
    """段方向（自接點向外）：回傳 (軸, 符號)。"""
    axes = [i for i in range(3) if abs(b[i] - a[i]) > 1e-9]
    if len(axes) != 1:
        return -1, 0
    for i in axes:
        d = b[i] - a[i]
        if abs(d) > 1e-9:
            return i, 1 if d > 0 else -1
    return -1, 0


def build_joints(segs: list[tuple[Vec, Vec]]) -> list[dict]:
    lens = {f"S{i + 1:03d}": math.dist(a, b) * 1000 for i, (a, b) in enumerate(segs)}
    ends: dict[tuple, list] = {}
    for idx, (a, b) in enumerate(segs):
        sid = f"S{idx + 1:03d}"
        ends.setdefault(tuple(round(v, 6) for v in a), []).append((sid, b))   # 自此點向外之另一端
        ends.setdefault(tuple(round(v, 6) for v in b), []).append((sid, a))
    joints = []
    for pt in sorted(k for k, v in ends.items() if len(v) >= 2):
        inc = ends[pt]
        dirs = [(sid, _dir(pt, other)) for sid, other in inc]
        j = {"point": _mm(pt), "segments": [sid for sid, _ in inc], "branch": None}
        if any(d[0] < 0 for _, d in dirs) or len({d for _, d in dirs}) != len(dirs):
            j["kind"] = "unsupported"
        elif len(inc) == 2:
            (_, d1), (_, d2) = dirs
            j["kind"] = "union" if (d1[0] == d2[0] and d1[1] == -d2[1]) else "elbow"
        elif len(inc) == 3:
            mains = [(s, d) for s, d in dirs for s2, d2 in dirs
                     if s != s2 and d[0] == d2[0] and d[1] == -d2[1]]
            main_ids = sorted({s for s, _ in mains})
            if len(main_ids) == 2:
                j["kind"], j["branch"] = "tee", next(s for s, _ in dirs if s not in main_ids)
                j["segments"] = main_ids + [j["branch"]]          # 順序：主幹 2 段 + 支線（NewTeeFitting 用）
            else:
                j["kind"] = "unsupported"
        elif len(inc) == 4:
            ax = {}
            for s, d in dirs:
                ax.setdefault(d[0], []).append(s)
            ok = (sorted(len(v) for v in ax.values()) == [2, 2]
                  and all({d[1] for _, d in dirs if d[0] == axis} == {-1, 1}
                          for axis in ax))
            j["kind"] = "cross" if ok else "unsupported"
            if ok:
                j["segments"] = [s for v in ax.values() for s in v]
        else:
            j["kind"] = "unsupported"
        joints.append(j)
    for n, j in enumerate(joints, 1):
        j["id"] = f"J{n:03d}"
        j[FIELDS["MinLegMm"]] = round(min(lens[s] for s in j["segments"]), 3) + 0.0   # 相鄰段最短長度，供失敗原因判讀
    return joints


def _nearest_segment_id(pt, segs) -> str:
    def d(seg):
        a, b = seg
        t = [b[i] - a[i] for i in range(3)]
        L2 = sum(x * x for x in t) or 1e-12
        u = max(0.0, min(1.0, sum((pt[i] - a[i]) * t[i] for i in range(3)) / L2))
        q = [a[i] + t[i] * u for i in range(3)]
        return math.dist(pt, q)
    return f"S{min(range(len(segs)), key=lambda i: (d(segs[i]), i)) + 1:03d}"


def coordinate_system(basis: str = "UNSPECIFIED") -> dict:
    if basis not in BASES:
        raise ValueError(f"basis 需為 {BASES}")
    return {"basis": basis, "origin": [0.0, 0.0, 0.0], "unit": "mm",
            "axis_x": [1.0, 0.0, 0.0], "axis_y": [0.0, 1.0, 0.0], "axis_z": [0.0, 0.0, 1.0],
            "rotation_deg": 0.0,
            "note": "原點=輸入座標系原點（不平移）。對應 Revit 的哪一個基準由 basis 指定；UNSPECIFIED 時匯入器拒絕執行。"}


def build_model(inp: Inputs, route: Route, reports: list, gov: dict, run_id: str,
                type_name: str | None = None, basis: str = "UNSPECIFIED", notes=()) -> dict:
    segs = split_segments(route)
    findings = []
    for rep in reports:
        for f in rep.findings:
            d = f.to_dict()
            d[FIELDS["SegmentId"]] = _nearest_segment_id(f.location, segs) if segs else None
            findings.append(d)
    disc = base_notes(inp, gov, reports, notes)
    disc.append(REVIT_STATUS)
    warnings = [f"{sid} 長度 {math.dist(a, b) * 1000:.3f} mm 小於 Revit 最短線段 {REVIT_MIN_SEGMENT_MM} mm，匯入時會整批回滾"
                for sid, (a, b) in ((f"S{i + 1:03d}", sg) for i, sg in enumerate(segs))
                if math.dist(a, b) * 1000 < REVIT_MIN_SEGMENT_MM]
    return {
        FIELDS["SchemaVersion"]: SCHEMA_VERSION, FIELDS["RunId"]: run_id, FIELDS["Units"]: "mm",
        FIELDS["CoordinateSystem"]: coordinate_system(basis),
        FIELDS["Tray"]: {FIELDS["TypeName"]: type_name, FIELDS["WidthMm"]: inp.tray_w_mm,
                         FIELDS["HeightMm"]: inp.tray_h_mm, FIELDS["Kind"]: inp.tray_type},
        FIELDS["Segments"]: [{FIELDS["Id"]: f"S{i + 1:03d}", FIELDS["Start"]: _mm(a), FIELDS["End"]: _mm(b)}
                             for i, (a, b) in enumerate(segs)],
        FIELDS["Joints"]: build_joints(segs),
        FIELDS["Hangers"]: [_mm(p) for p in route.hangers],
        FIELDS["Findings"]: findings,
        FIELDS["Disclosures"]: disc,
        FIELDS["Warnings"]: warnings,
    }


def write_model(model: dict, run_id: str, name: str | None = None, overwrite: bool = False,
                base: Path | None = None) -> Path:
    path = out_path(run_id, name or f"tray_{run_id}.json", base)
    if path.exists() and not overwrite:
        raise FileExistsError(f"輸出檔已存在，拒絕覆寫: {path.name}")
    path.write_text(json.dumps(model, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    return path


# ---- Comments 區段（與 C# MepTray.Core.Comments 行為一致）----
_SECTION_RE = re.compile(re.escape(TAG_OPEN) + r".*?" + re.escape(TAG_CLOSE), re.S)


def merge_comments(old: str | None, section_body: str) -> str:
    """保留原 Comments；已有 [MEP-TRAY] 區段則就地更新，否則附加。重複呼叫結果不變（冪等）。"""
    old = old or ""
    sec = f"{TAG_OPEN} {section_body} {TAG_CLOSE}"
    if _SECTION_RE.search(old):
        return _SECTION_RE.sub(lambda m: sec, old, count=1)
    return (old + ("\n" if old and not old.endswith("\n") else "") + sec)


def comment_body(model: dict, seg_id: str) -> str:
    fs = [f for f in model[FIELDS["Findings"]] if f.get(FIELDS["SegmentId"]) == seg_id]
    head = f"RUN={model[FIELDS['RunId']]}; SEG={seg_id}; TYPE={model[FIELDS['Tray']][FIELDS['Kind']]}"
    if not fs:
        return head
    items = "; ".join(f"{f['status']} {f['kind']} {f['code'] or '-'}" for f in fs)
    return f"{head}; FINDINGS={items}"
